CC = gcc
LD = gcc
AS = nasm

CFLAGS = -c
#CFLAGS = -c -DNO_XPM
#CFLAGS = -c -DHAVE_SDL2
LFLAGS = -lX11 -lXpm
#LFLAGS = -lX11
#LFLAGS = -lX11 -lXpm -lSDL2
AFLAGS = -f elf64

all: fractald fractalf

fractald: fractald.o routinesd.o
	$(LD) fractald.o routinesd.o -o fractald $(LFLAGS)

fractalf: fractalf.o routinesf.o
	$(LD) fractalf.o routinesf.o -o fractalf $(LFLAGS)

routinesd.o: routinesd.asm
	$(AS) $(AFLAGS) routinesd.asm

routinesf.o: routinesf.asm
	$(AS) $(AFLAGS) routinesf.asm

fractald.o: fractald.c 
	$(CC) $(CFLAGS) fractald.c

fractalf.o: fractalf.c 
	$(CC) $(CFLAGS) fractalf.c

clean:
	rm -f *.o fractald fractalf
